using System.Text.Json;
using HarborOfHope.API.Data;
using HarborOfHope.API.Data.Entities;
using HarborOfHope.API.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HarborOfHope.API.Controllers;

/// <summary>
/// Serves explanatory ML insights from PostgreSQL tables.
/// Results are generated by Python script: jobs/run_explanatory_insights.py
/// </summary>
[ApiController]
[Route("api/[controller]")]
[Authorize(Policy = AuthPolicies.AdminOnly)]
public class ExplanatoryInsightsController(AppDbContext db) : ControllerBase
{
    [HttpGet]
    public async Task<ActionResult<List<ExplanatoryPipelineDto>>> GetAllInsights()
    {
        var insights = await db.ExplanatoryInsights
            .OrderBy(i => i.PipelineId)
            .ToListAsync();

        var features = await db.ExplanatoryFeatures
            .OrderBy(f => f.FeatureRank)
            .ToListAsync();

        var featuresByPipeline = features
            .GroupBy(f => f.PipelineId)
            .ToDictionary(g => g.Key, g => g.ToList());

        var result = insights.Select(i => MapToDto(i, featuresByPipeline)).ToList();
        return Ok(result);
    }

    [HttpGet("{pipelineId:int}")]
    public async Task<ActionResult<ExplanatoryPipelineDto>> GetInsight(int pipelineId)
    {
        var insight = await db.ExplanatoryInsights
            .FirstOrDefaultAsync(i => i.PipelineId == pipelineId);

        if (insight is null) return NotFound();

        var features = await db.ExplanatoryFeatures
            .Where(f => f.PipelineId == pipelineId)
            .OrderBy(f => f.FeatureRank)
            .ToListAsync();

        var featuresByPipeline = new Dictionary<int, List<ExplanatoryFeature>>
        {
            [pipelineId] = features
        };

        return Ok(MapToDto(insight, featuresByPipeline));
    }

    private static ExplanatoryPipelineDto MapToDto(
        ExplanatoryInsight insight,
        Dictionary<int, List<ExplanatoryFeature>> featuresByPipeline)
    {
        var recommendations = new List<string>();
        try
        {
            recommendations = JsonSerializer.Deserialize<List<string>>(
                insight.RecommendationsJson ?? "[]") ?? [];
        }
        catch { /* fallback to empty */ }

        featuresByPipeline.TryGetValue(insight.PipelineId, out var pipelineFeatures);

        var topFeatures = (pipelineFeatures ?? []).Select(f =>
            new ExplanatoryFeatureDto(
                Name: f.FeatureName,
                Coefficient: f.Coefficient,
                PValue: f.PValue,
                Direction: f.Direction,
                Interpretation: f.Interpretation,
                IsSignificant: f.IsSignificant
            )).ToList();

        return new ExplanatoryPipelineDto(
            PipelineId: insight.PipelineId,
            PipelineName: insight.PipelineName,
            TargetVariable: insight.TargetVariable,
            ModelType: insight.ModelType,
            RSquared: insight.RSquared,
            AdjRSquared: insight.AdjRSquared,
            SampleSize: insight.SampleSize,
            KeyInsight: insight.KeyInsight,
            Recommendations: recommendations,
            TopFeatures: topFeatures
        );
    }
}
