"""Build script for 05-incident-risk-prediction.ipynb"""
import json

def md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

def code(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

cells = [

# ── Section 1: Problem Framing ───────────────────────────────────────────────
md([
    "# Notebook 05: Incident Risk Prediction\n",
    "\n",
    "## Section 1 - Problem Framing\n",
    "\n",
    "**Business Problem:** Predict which residents are at higher risk of experiencing behavioral, medical, or security incidents so that social workers can allocate monitoring resources proactively rather than reactively.\n",
    "\n",
    "**Why it matters:** Without a data-driven signal, case managers rely on intuition and self-reported assessments to prioritize check-ins. A model that surfaces high-risk resident profiles gives staff an objective second opinion at intake and during ongoing case reviews.\n",
    "\n",
    "**Approach:** Predictive binary classification. The target is whether a resident has ever appeared in `incident_reports` (1 = has incident history, 0 = no recorded incidents). With only 60 residents in the current dataset, we frame this as a resident-profile prediction — the model learns which combinations of intake characteristics and service engagement patterns associate with incident occurrence.\n",
    "\n",
    "**Important constraint:** Features derived from cumulative service records (session count, visit count) reflect a resident's full history rather than their state at intake. This is acknowledged in the Limitations section. The model is most useful as a *profile-similarity* tool — flagging new residents whose characteristics resemble historically high-incident residents — rather than a real-time predictor.\n",
    "\n",
    "**Target Distribution:** 44 out of 60 residents have incidents (73%), 16 do not (27%). This is a moderately imbalanced dataset favoring the positive class.\n",
    "\n",
    "**Success Metric:** F1 score and AUC-ROC. High recall is prioritized — missing a high-risk resident is more costly than flagging a low-risk one for extra monitoring.\n",
    "\n",
    "**Stakeholders:** Social workers, safehouse administrators, case managers.\n",
    "\n",
    "**Model Progression:** LogisticRegression (baseline) -> DecisionTree -> RandomForest -> GradientBoosting, selecting the best by cross-validated ROC-AUC.",
]),

# ── Section 2: Data Acquisition ───────────────────────────────────────────────
md(["## Section 2 - Data Acquisition, Preparation & Exploration"]),

code([
    "%matplotlib inline\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "DATA = '../../data/lighthouse_csv_v7/'\n",
    "\n",
    "residents   = pd.read_csv(DATA + 'residents.csv')\n",
    "health      = pd.read_csv(DATA + 'health_wellbeing_records.csv')\n",
    "education   = pd.read_csv(DATA + 'education_records.csv')\n",
    "process_rec = pd.read_csv(DATA + 'process_recordings.csv')\n",
    "visitations = pd.read_csv(DATA + 'home_visitations.csv')\n",
    "incidents   = pd.read_csv(DATA + 'incident_reports.csv')\n",
    "\n",
    "print(f'Residents:          {len(residents)} rows')\n",
    "print(f'Health records:     {len(health)} rows')\n",
    "print(f'Education records:  {len(education)} rows')\n",
    "print(f'Process recordings: {len(process_rec)} rows')\n",
    "print(f'Home visitations:   {len(visitations)} rows')\n",
    "print(f'Incident reports:   {len(incidents)} rows')",
]),

md([
    "### Raw Data Exploration\n",
    "\n",
    "Before any transformation we inspect all six tables for shape, data types, and missing values.\n",
    "This documents the state of the data before preparation so that every decision is traceable.",
]),

code([
    "# --- Residents table ---\n",
    "print('=== Residents ===')\n",
    "print(f'Shape: {residents.shape}')\n",
    "print(f'\\nData types:\\n{residents.dtypes}')\n",
    "print(f'\\nMissing values:\\n{residents.isnull().sum()}')\n",
    "print(f\"\\nInitial risk levels:\\n{residents['initial_risk_level'].value_counts()}\")\n",
    "print(f\"\\nCase categories:\\n{residents['case_category'].value_counts()}\")",
]),

code([
    "# --- Incident reports table ---\n",
    "print('=== Incident Reports ===')\n",
    "print(f'Shape: {incidents.shape}')\n",
    "print(f'\\nMissing values:\\n{incidents.isnull().sum()}')\n",
    "print(f\"\\nUnique residents with incidents: {incidents['resident_id'].nunique()}\")\n",
    "print(f\"\\nIncidents per resident (top 10):\\n{incidents['resident_id'].value_counts().head(10)}\")",
]),

code([
    "# --- Supporting tables: shape and missing values ---\n",
    "for name, tbl in [('Health', health), ('Education', education),\n",
    "                   ('Process Recordings', process_rec), ('Visitations', visitations)]:\n",
    "    print(f'=== {name} ===')\n",
    "    print(f'Shape: {tbl.shape}')\n",
    "    missing = tbl.isnull().sum()\n",
    "    print(f'Missing values:\\n{missing[missing > 0] if missing.any() else \"None\"}')\n",
    "    print()",
]),

md([
    "### Data Preparation & Feature Engineering\n",
    "\n",
    "**Modeling unit:** One row = one resident. We predict `has_incident` — whether a resident has any entry in `incident_reports`.\n",
    "\n",
    "**Why resident-level?**\n",
    "There are only 60 residents. Aggregating to the resident level preserves all signal while keeping the dataset at its natural granularity for the prediction task (flagging individuals).\n",
    "\n",
    "**Join rationale:**\n",
    "- `health_wellbeing_records` -> averaged per resident: captures typical health trajectory\n",
    "- `education_records` -> averaged per resident: attendance and progress as proxies for engagement/stability\n",
    "- `process_recordings` -> count and average duration: service intensity received\n",
    "- `home_visitations` -> count: external support network activity\n",
    "- All joins are left joins on `resident_id` to preserve all 60 residents\n",
    "\n",
    "**Missing value handling:**\n",
    "Two residents have no visitation records. Rather than dropping them or imputing outside the pipeline,\n",
    "`SimpleImputer(strategy='median')` inside the sklearn pipeline handles all imputation — ensuring\n",
    "no leakage from test-fold data into training during cross-validation.",
]),

code([
    "# Create target: has_incident = 1 if resident appears in incident_reports\n",
    "incident_ids = set(incidents['resident_id'].unique())\n",
    "residents_df = residents[['resident_id', 'safehouse_id', 'initial_risk_level',\n",
    "                            'case_category', 'date_enrolled']].copy()\n",
    "residents_df['has_incident'] = residents_df['resident_id'].apply(\n",
    "    lambda x: 1 if x in incident_ids else 0\n",
    ")\n",
    "\n",
    "print('Target distribution:')\n",
    "print(residents_df['has_incident'].value_counts())\n",
    "print(f\"Incident rate: {residents_df['has_incident'].mean():.2%}\")",
]),

code([
    "# Aggregate per-resident features\n",
    "\n",
    "health_agg = health.groupby('resident_id').agg(\n",
    "    avg_health_score=('general_health_score', 'mean')\n",
    ").reset_index()\n",
    "\n",
    "edu_agg = education.groupby('resident_id').agg(\n",
    "    avg_education_attendance=('attendance_rate', 'mean'),\n",
    "    avg_education_progress=('progress_percent', 'mean')\n",
    ").reset_index()\n",
    "\n",
    "session_agg = process_rec.groupby('resident_id').agg(\n",
    "    session_count=('recording_id', 'count'),\n",
    "    avg_session_duration=('session_duration_minutes', 'mean')\n",
    ").reset_index()\n",
    "\n",
    "visit_agg = visitations.groupby('resident_id').agg(\n",
    "    visit_count=('visitation_id', 'count')\n",
    ").reset_index()\n",
    "\n",
    "# Length of stay computed from enrollment to reference date\n",
    "residents_df['date_enrolled'] = pd.to_datetime(residents_df['date_enrolled'])\n",
    "reference_date = pd.Timestamp('2026-03-31')\n",
    "residents_df['length_of_stay'] = (reference_date - residents_df['date_enrolled']).dt.days\n",
    "\n",
    "print(f'Aggregation complete.')\n",
    "print(f'Health: {len(health_agg)}, Education: {len(edu_agg)}')\n",
    "print(f'Sessions: {len(session_agg)}, Visits: {len(visit_agg)}')",
]),

code([
    "# Merge all features (left join preserves all 60 residents)\n",
    "df = residents_df.copy()\n",
    "df = df.merge(health_agg,   on='resident_id', how='left')\n",
    "df = df.merge(edu_agg,      on='resident_id', how='left')\n",
    "df = df.merge(session_agg,  on='resident_id', how='left')\n",
    "df = df.merge(visit_agg,    on='resident_id', how='left')\n",
    "\n",
    "# NaN imputation is handled inside the sklearn pipeline (SimpleImputer)\n",
    "# We do NOT fill NaN here to avoid leaking test-fold medians into training\n",
    "\n",
    "numeric_features     = ['avg_health_score', 'avg_education_attendance', 'avg_education_progress',\n",
    "                         'session_count', 'avg_session_duration', 'visit_count', 'length_of_stay']\n",
    "categorical_features = ['initial_risk_level', 'case_category']\n",
    "\n",
    "print(f'Final dataset shape: {df.shape}')\n",
    "print(f'\\nMissing values before pipeline imputation:')\n",
    "print(df[numeric_features + categorical_features].isnull().sum())\n",
    "df.head()",
]),

md([
    "### Univariate Feature Analysis\n",
    "\n",
    "We examine distributions, group differences by incident status, and correlations with the target\n",
    "before making any modeling decisions.",
]),

code([
    "# Feature distributions\n",
    "fig, axes = plt.subplots(2, 4, figsize=(18, 9))\n",
    "\n",
    "df['has_incident'].value_counts().plot(\n",
    "    kind='bar', ax=axes[0, 0], color=['#4CAF50', '#E8735A']\n",
    ")\n",
    "axes[0, 0].set_title('Incident Distribution')\n",
    "axes[0, 0].set_xticklabels(['No Incident (0)', 'Has Incident (1)'], rotation=0)\n",
    "\n",
    "for i, col in enumerate(['avg_health_score', 'avg_education_attendance',\n",
    "                           'avg_education_progress', 'session_count',\n",
    "                           'visit_count', 'length_of_stay']):\n",
    "    ax = axes.flat[i + 1]\n",
    "    df[col].hist(bins=15, ax=ax, color='#5B9BD5', edgecolor='white')\n",
    "    ax.set_title(col)\n",
    "\n",
    "plt.suptitle('Feature Distributions', fontsize=13, y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig('distributions_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()",
]),

code([
    "# Boxplots: numeric features split by incident status\n",
    "# 3x3 grid: 7 numeric boxplots + 2 categorical bar charts = 9 panels\n",
    "fig, axes = plt.subplots(3, 3, figsize=(18, 14))\n",
    "\n",
    "for i, col in enumerate(numeric_features):\n",
    "    ax = axes.flat[i]\n",
    "    df.boxplot(column=col, by='has_incident', ax=ax)\n",
    "    ax.set_title(col)\n",
    "    ax.set_xlabel('Has Incident')\n",
    "\n",
    "# Categorical: incident rate by risk level and case category\n",
    "for i, col in enumerate(categorical_features):\n",
    "    ax = axes.flat[len(numeric_features) + i]\n",
    "    means = df.groupby(col)['has_incident'].mean().sort_values(ascending=False)\n",
    "    means.plot(kind='bar', ax=ax, color='#E8735A', edgecolor='white')\n",
    "    ax.set_title(f'Incident Rate by {col}')\n",
    "    ax.set_ylabel('Incident Rate')\n",
    "    ax.tick_params(axis='x', rotation=30)\n",
    "\n",
    "plt.suptitle('Features vs Incident Status', fontsize=13, y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig('boxplots_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()",
]),

code([
    "# Correlation heatmap: numeric features vs target\n",
    "fig, ax = plt.subplots(figsize=(10, 8))\n",
    "corr = df[numeric_features + ['has_incident']].corr()\n",
    "sns.heatmap(corr, annot=True, fmt='.2f', cmap='coolwarm', center=0, linewidths=0.5, ax=ax)\n",
    "ax.set_title('Correlation Matrix: Numeric Features vs Incident Status')\n",
    "plt.tight_layout()\n",
    "plt.savefig('correlation_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()",
]),

md([
    "### Exploration Findings\n",
    "\n",
    "*(Update this narrative after running the cells above with actual observed values.)*\n",
    "\n",
    "**Target distribution:**\n",
    "73% of residents have at least one incident on record. The class imbalance is moderate;\n",
    "`class_weight='balanced'` is applied to applicable models to prevent the majority class from dominating.\n",
    "\n",
    "**Numeric features:**\n",
    "- `initial_risk_level` is expected to be the strongest predictor — it is the structured intake assessment.\n",
    "- `session_count` and `visit_count` show variation across incident groups but are cumulative over\n",
    "  the resident's stay, limiting their prospective value (see Limitations).\n",
    "- `avg_health_score` may be lower among higher-incident residents, consistent with co-occurring\n",
    "  health and behavioral challenges.\n",
    "- `length_of_stay` likely correlates with incident occurrence because longer-stay residents have\n",
    "  had more exposure time.\n",
    "\n",
    "**Categorical features:**\n",
    "- `initial_risk_level = Critical` is expected to have the highest incident rate.\n",
    "- `case_category` may differ between Neglected, Surrendered, and Abandoned residents,\n",
    "  reflecting case complexity.\n",
    "\n",
    "**Correlations:**\n",
    "Given the small sample (n=60), no individual correlation coefficient is highly stable.\n",
    "Permutation importance at the end of the pipeline provides a more reliable signal.",
]),

# ── Section 3: Modeling ───────────────────────────────────────────────────────
md(["## Section 3 - Modeling & Feature Selection"]),

md([
    "### Feature Selection Rationale\n",
    "\n",
    "Features selected on three criteria: (1) theoretical relevance to incident risk,\n",
    "(2) observed signal in exploration, and (3) no data leakage.\n",
    "\n",
    "| Feature | Type | Rationale |\n",
    "|---|---|---|\n",
    "| `avg_health_score` | Numeric | Physical health is directly linked to medical and behavioral incidents |\n",
    "| `avg_education_attendance` | Numeric | Attendance consistency reflects engagement and routine stability |\n",
    "| `avg_education_progress` | Numeric | Progress rate captures cognitive and behavioral development |\n",
    "| `session_count` | Numeric | Service intensity; residents receiving more sessions may have higher need |\n",
    "| `avg_session_duration` | Numeric | Session depth; longer sessions may indicate more complex cases |\n",
    "| `visit_count` | Numeric | External support; more visits may indicate higher monitoring |\n",
    "| `length_of_stay` | Numeric | Exposure time; longer stays provide more opportunity for incidents |\n",
    "| `initial_risk_level` | Categorical | Formal intake risk assessment — most direct predictor |\n",
    "| `case_category` | Categorical | Case type reflects nature of placement and associated risk profile |\n",
    "\n",
    "**Excluded:**\n",
    "- `safehouse_id` — facility identifier, not a resident characteristic; would introduce spurious facility-level effects\n",
    "- `date_enrolled` — raw date; replaced by the derived `length_of_stay`\n",
    "- `resident_id` — identifier, not a feature",
]),

code([
    "from sklearn.model_selection import StratifiedKFold\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.compose import ColumnTransformer\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.model_selection import cross_validate\n",
    "\n",
    "X = df[numeric_features + categorical_features].copy()\n",
    "y = df['has_incident'].copy()\n",
    "\n",
    "# Preprocessing: impute then scale/encode -- all inside the pipeline to prevent leakage\n",
    "numeric_pipe = Pipeline([\n",
    "    ('impute', SimpleImputer(strategy='median')),\n",
    "    ('scale',  StandardScaler()),\n",
    "])\n",
    "\n",
    "categorical_pipe = Pipeline([\n",
    "    ('impute', SimpleImputer(strategy='most_frequent')),\n",
    "    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False)),\n",
    "])\n",
    "\n",
    "preprocessor = ColumnTransformer([\n",
    "    ('num', numeric_pipe,     numeric_features),\n",
    "    ('cat', categorical_pipe, categorical_features),\n",
    "])\n",
    "\n",
    "# 10-fold StratifiedKFold -- more folds = more training data per fold with small n\n",
    "# With n=60, 10-fold gives ~54 training / 6 test per fold vs 48/12 with a single split\n",
    "skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)\n",
    "\n",
    "print(f'Dataset: {X.shape[0]} samples, {X.shape[1]} features')\n",
    "print(f'Incident rate: {y.mean():.2%}  ({y.sum()} with incidents, {(y==0).sum()} without)')\n",
    "print(f'CV strategy: {skf.n_splits}-fold StratifiedKFold (primary evaluation)')\n",
    "print('Note: No held-out test set -- n=60 makes a 12-sample holdout statistically unreliable.')\n",
    "print('Cross-validation results are used as the primary performance estimate.')",
]),

code([
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "model_lr = Pipeline([\n",
    "    ('prep', preprocessor),\n",
    "    ('lr',   LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)),\n",
    "])\n",
    "\n",
    "scoring = {\n",
    "    'accuracy':          'accuracy',\n",
    "    'balanced_accuracy': 'balanced_accuracy',\n",
    "    'f1':                'f1',\n",
    "    'roc_auc':           'roc_auc',\n",
    "    'neg_log_loss':      'neg_log_loss',\n",
    "}\n",
    "\n",
    "cv_lr = cross_validate(model_lr, X, y, cv=skf, scoring=scoring, n_jobs=-1)\n",
    "\n",
    "print('Logistic Regression Baseline -- 10-Fold Cross-Validation')\n",
    "print('-' * 55)\n",
    "for key, vals in cv_lr.items():\n",
    "    if key.startswith('test_'):\n",
    "        metric = key.replace('test_', '')\n",
    "        mean = vals.mean() * (-1 if metric == 'neg_log_loss' else 1)\n",
    "        print(f'  {metric:<22} {mean:.4f} +/- {vals.std():.4f}')",
]),

code([
    "from sklearn.model_selection import learning_curve\n",
    "\n",
    "train_sizes, train_scores, val_scores = learning_curve(\n",
    "    model_lr, X, y,\n",
    "    cv=skf,\n",
    "    scoring='roc_auc',\n",
    "    train_sizes=np.linspace(0.2, 1.0, 8),\n",
    "    n_jobs=-1,\n",
    ")\n",
    "\n",
    "train_mean = train_scores.mean(axis=1)\n",
    "train_std  = train_scores.std(axis=1)\n",
    "val_mean   = val_scores.mean(axis=1)\n",
    "val_std    = val_scores.std(axis=1)\n",
    "\n",
    "plt.figure(figsize=(8, 5))\n",
    "plt.plot(train_sizes, train_mean, marker='o', label='Training ROC AUC')\n",
    "plt.fill_between(train_sizes, train_mean - train_std, train_mean + train_std, alpha=0.2)\n",
    "plt.plot(train_sizes, val_mean, marker='o', label='Validation ROC AUC (CV)')\n",
    "plt.fill_between(train_sizes, val_mean - val_std, val_mean + val_std, alpha=0.2)\n",
    "plt.title('Learning Curve: Logistic Regression')\n",
    "plt.xlabel('Training set size')\n",
    "plt.ylabel('ROC AUC')\n",
    "plt.legend()\n",
    "plt.grid(True)\n",
    "plt.tight_layout()\n",
    "plt.savefig('learning_curve_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()\n",
    "\n",
    "gap = train_mean[-1] - val_mean[-1]\n",
    "print(f'Final training ROC AUC:   {train_mean[-1]:.4f}')\n",
    "print(f'Final validation ROC AUC: {val_mean[-1]:.4f}')\n",
    "print(f'Gap (overfitting signal): {gap:.4f}')",
]),

code([
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "\n",
    "models = {\n",
    "    'LogisticRegression': Pipeline([\n",
    "        ('prep', preprocessor),\n",
    "        ('lr',   LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)),\n",
    "    ]),\n",
    "    'DecisionTree': Pipeline([\n",
    "        ('prep', preprocessor),\n",
    "        ('dt',   DecisionTreeClassifier(max_depth=4, class_weight='balanced', random_state=42)),\n",
    "    ]),\n",
    "    'RandomForest': Pipeline([\n",
    "        ('prep', preprocessor),\n",
    "        ('rf',   RandomForestClassifier(n_estimators=100, class_weight='balanced',\n",
    "                                         random_state=42, n_jobs=-1)),\n",
    "    ]),\n",
    "    'GradientBoosting': Pipeline([\n",
    "        ('prep', preprocessor),\n",
    "        ('gb',   GradientBoostingClassifier(n_estimators=100, max_depth=3, random_state=42)),\n",
    "    ]),\n",
    "}\n",
    "\n",
    "results_list = []\n",
    "for name, model in models.items():\n",
    "    cv_res = cross_validate(model, X, y, cv=skf, scoring=scoring, n_jobs=-1)\n",
    "    row = {'Model': name}\n",
    "    for key, vals in cv_res.items():\n",
    "        if key.startswith('test_'):\n",
    "            metric = key.replace('test_', '')\n",
    "            row[f'{metric}_mean'] = vals.mean() * (-1 if metric == 'neg_log_loss' else 1)\n",
    "            row[f'{metric}_std']  = vals.std()\n",
    "    results_list.append(row)\n",
    "\n",
    "comparison_df = pd.DataFrame(results_list).sort_values('roc_auc_mean', ascending=False).reset_index(drop=True)\n",
    "\n",
    "print('Model Comparison -- 10-Fold CV (sorted by ROC AUC)')\n",
    "print('=' * 70)\n",
    "for _, row in comparison_df.iterrows():\n",
    "    print(f\"{row['Model']:<22} | Acc: {row['accuracy_mean']:.3f} | \"\n",
    "          f\"F1: {row['f1_mean']:.3f} | ROC AUC: {row['roc_auc_mean']:.3f} +/- {row['roc_auc_std']:.3f}\")",
]),

code([
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "best_model_name = comparison_df.iloc[0]['Model']\n",
    "print(f'Best model from comparison: {best_model_name}')\n",
    "print(f\"CV ROC AUC: {comparison_df.iloc[0]['roc_auc_mean']:.4f}\")\n",
    "print('Running GridSearchCV...\\n')\n",
    "\n",
    "tuning_configs = {\n",
    "    'LogisticRegression': {\n",
    "        'pipeline': Pipeline([('prep', preprocessor),\n",
    "                              ('lr', LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42))]),\n",
    "        'param_grid': {'lr__C': [0.01, 0.1, 1.0, 10.0], 'lr__penalty': ['l2']},\n",
    "    },\n",
    "    'DecisionTree': {\n",
    "        'pipeline': Pipeline([('prep', preprocessor),\n",
    "                              ('dt', DecisionTreeClassifier(class_weight='balanced', random_state=42))]),\n",
    "        'param_grid': {'dt__max_depth': [2, 3, 4, 5], 'dt__min_samples_leaf': [1, 2, 3]},\n",
    "    },\n",
    "    'RandomForest': {\n",
    "        'pipeline': Pipeline([('prep', preprocessor),\n",
    "                              ('rf', RandomForestClassifier(class_weight='balanced', random_state=42, n_jobs=-1))]),\n",
    "        'param_grid': {'rf__n_estimators': [50, 100, 200],\n",
    "                       'rf__max_depth': [2, 3, 4, 5],\n",
    "                       'rf__min_samples_leaf': [1, 2, 3]},\n",
    "    },\n",
    "    'GradientBoosting': {\n",
    "        'pipeline': Pipeline([('prep', preprocessor),\n",
    "                              ('gb', GradientBoostingClassifier(random_state=42))]),\n",
    "        'param_grid': {'gb__n_estimators': [50, 100, 200],\n",
    "                       'gb__max_depth': [2, 3, 4],\n",
    "                       'gb__learning_rate': [0.05, 0.1, 0.2]},\n",
    "    },\n",
    "}\n",
    "\n",
    "config = tuning_configs[best_model_name]\n",
    "grid_search = GridSearchCV(\n",
    "    estimator=config['pipeline'],\n",
    "    param_grid=config['param_grid'],\n",
    "    cv=skf,\n",
    "    scoring='roc_auc',\n",
    "    n_jobs=-1,\n",
    ")\n",
    "grid_search.fit(X, y)\n",
    "\n",
    "print(f'Best parameters: {grid_search.best_params_}')\n",
    "print(f'Best CV ROC AUC: {grid_search.best_score_:.4f}')\n",
    "\n",
    "best_pipeline = grid_search.best_estimator_",
]),

# ── Section 4: Evaluation ─────────────────────────────────────────────────────
md([
    "## Section 4 - Evaluation & Selection\n",
    "\n",
    "**Primary evaluation method: 10-fold cross-validation on all 60 residents.**\n",
    "\n",
    "With n=60, a held-out test set of ~12 samples (only ~3 negative-class residents) produces metrics\n",
    "with confidence intervals so wide they are not meaningful — as demonstrated in the original version\n",
    "of this notebook, where the test-set evaluation showed 0% recall on the negative class and\n",
    "AUC = 0.56 on just 12 observations.\n",
    "\n",
    "`cross_val_predict` generates out-of-fold predictions for every resident without a separate test set,\n",
    "giving a confusion matrix and ROC curve that represent the full dataset.",
]),

code([
    "from sklearn.metrics import classification_report, ConfusionMatrixDisplay, roc_auc_score, roc_curve\n",
    "from sklearn.model_selection import cross_val_predict\n",
    "\n",
    "y_pred  = cross_val_predict(best_pipeline, X, y, cv=skf, method='predict')\n",
    "y_proba = cross_val_predict(best_pipeline, X, y, cv=skf, method='predict_proba')[:, 1]\n",
    "\n",
    "print(f'Classification Report (10-fold cross-validated, all {len(y)} residents):')\n",
    "print(classification_report(y, y_pred, target_names=['No Incident', 'Has Incident']))",
]),

code([
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n",
    "\n",
    "ConfusionMatrixDisplay.from_predictions(\n",
    "    y, y_pred,\n",
    "    display_labels=['No Incident', 'Has Incident'],\n",
    "    ax=axes[0], cmap='Blues',\n",
    ")\n",
    "axes[0].set_title('Confusion Matrix (10-Fold CV, all residents)')\n",
    "\n",
    "auc = roc_auc_score(y, y_proba)\n",
    "fpr, tpr, _ = roc_curve(y, y_proba)\n",
    "axes[1].plot(fpr, tpr, color='#E8735A', linewidth=2, label=f'AUC = {auc:.4f}')\n",
    "axes[1].plot([0, 1], [0, 1], 'k--', alpha=0.5)\n",
    "axes[1].set_xlabel('False Positive Rate')\n",
    "axes[1].set_ylabel('True Positive Rate')\n",
    "axes[1].set_title('ROC Curve (10-Fold CV)')\n",
    "axes[1].legend()\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('evaluation_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(f'ROC-AUC (CV): {auc:.4f}')",
]),

md([
    "### Limitations\n",
    "\n",
    "**Sample size is the primary constraint.** With 60 residents, no evaluation method produces\n",
    "highly reliable performance estimates:\n",
    "- Standard deviations across folds are large; results depend on which residents land in which fold\n",
    "- Feature importance rankings may shift considerably with more data\n",
    "- The model should be treated as a **directional tool** — the probability score (0-1) is useful\n",
    "  for ranking residents by risk even if exact calibration is imperfect\n",
    "\n",
    "**Cumulative feature bias:** `session_count`, `visit_count`, and `length_of_stay` are computed over\n",
    "a resident's *full* history. Longer-stay residents have had more opportunity to accumulate incidents,\n",
    "so these features partially reflect exposure time rather than inherent risk. Rate-normalized versions\n",
    "(e.g., sessions per month of stay) would be more prospectively valid.\n",
    "\n",
    "**Reporting bias:** Some safehouses or social workers may document incidents more thoroughly\n",
    "than others. The model will learn facility-level documentation patterns as well as resident risk.\n",
    "\n",
    "**`initial_risk_level` dominance:** The intake risk assessment is likely the single strongest\n",
    "predictor because it directly encodes the organization's prior judgment about each resident.\n",
    "It is worth verifying whether the model outperforms simply using `initial_risk_level` alone\n",
    "as a baseline rule.\n",
    "\n",
    "**What improves over time:** As the resident population grows, rerunning this pipeline will\n",
    "produce progressively more stable results. The methodology does not need to change, only\n",
    "the data volume.",
]),

md([
    "### Business Interpretation\n",
    "\n",
    "**False Negative (missed high-risk resident):** Model predicts low risk; resident experiences\n",
    "an incident without enhanced monitoring. This is the most costly error — delayed intervention\n",
    "can escalate a manageable situation.\n",
    "\n",
    "**False Positive (unnecessary monitoring):** Model flags a stable resident as high-risk.\n",
    "Staff allocate extra check-ins to someone who did not need them. Cost is low — some wasted effort.\n",
    "\n",
    "**Implication:** Recall matters more than precision for this use case. We would rather over-flag\n",
    "and do an unnecessary check-in than silently miss a resident heading toward a crisis. Use the\n",
    "predicted *probability score* (not just the binary label) to triage — a resident at 0.9\n",
    "probability should be prioritized over one at 0.55.\n",
    "\n",
    "**Causal caution:** Correlation does not imply causation:\n",
    "- `initial_risk_level` may reflect referral bias (higher-risk referrals get more monitoring,\n",
    "  leading to more *documented* incidents)\n",
    "- `session_count` could be both a risk signal (residents with more issues get more sessions)\n",
    "  and a protective factor (more sessions = better support)\n",
    "- Seasonal effects and pre-existing conditions not captured in the data are potential confounders\n",
    "\n",
    "**Actionable recommendations:**\n",
    "1. Flag new residents with Critical initial risk levels for enhanced monitoring in the first 30 days\n",
    "2. Use model output as one input alongside social worker judgment, not as a sole determinant\n",
    "3. Standardize incident reporting across safehouses to reduce documentation bias\n",
    "4. Investigate whether increased session frequency correlates with reduced incident rates over time",
]),

code([
    "from sklearn.inspection import permutation_importance\n",
    "\n",
    "# Fit on all data for final importance estimate\n",
    "best_pipeline.fit(X, y)\n",
    "\n",
    "perm = permutation_importance(\n",
    "    best_pipeline, X, y,\n",
    "    n_repeats=10, random_state=42, scoring='roc_auc',\n",
    ")\n",
    "\n",
    "imp_df = pd.DataFrame({\n",
    "    'Feature':    list(X.columns),\n",
    "    'Importance': perm.importances_mean,\n",
    "    'Std':        perm.importances_std,\n",
    "}).sort_values('Importance', ascending=True)\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(10, 6))\n",
    "ax.barh(imp_df['Feature'], imp_df['Importance'],\n",
    "        xerr=imp_df['Std'], color='#5B9BD5', edgecolor='white')\n",
    "ax.set_title(f'Permutation Feature Importance (ROC AUC decrease) -- {best_model_name}')\n",
    "ax.set_xlabel('Mean ROC AUC Decrease')\n",
    "plt.tight_layout()\n",
    "plt.savefig('importance_05.png', dpi=80, bbox_inches='tight')\n",
    "plt.show()\n",
    "print(imp_df.to_string(index=False))",
]),

# ── Section 5: Deployment ─────────────────────────────────────────────────────
md([
    "## Section 5 - Deployment & Integration\n",
    "\n",
    "**Deployment Architecture:** Pre-computed predictions written to PostgreSQL.\n",
    "\n",
    "This model is deployed as an offline batch pipeline. The production workflow is:\n",
    "\n",
    "1. **ETL:** `jobs/etl_incident_risk.py` reads residents, incident_reports, and related tables\n",
    "   from PostgreSQL, engineers features, and writes the `ml_incident_risk_features` table.\n",
    "2. **Train:** `jobs/train_incident_risk.py` trains the sklearn Pipeline, saves the model as\n",
    "   `artifacts/incident_risk.sav` along with `metadata.json` and `metrics.json`.\n",
    "3. **Inference:** `jobs/run_inference_incident_risk.py` loads the trained model, predicts incident\n",
    "   risk for all residents, and writes results to the `incident_risk_predictions` table in PostgreSQL.\n",
    "\n",
    "The .NET backend queries `incident_risk_predictions` via EF Core. The frontend surfaces risk scores\n",
    "on the resident management dashboard via `GET /api/predictions/incident-risk`, giving case managers\n",
    "a ranked list of residents to prioritize for check-ins.\n",
    "\n",
    "**Model type:** Predictive binary classification.",
]),

code([
    "import joblib\n",
    "\n",
    "# Final model fit on all available data\n",
    "best_pipeline.fit(X, y)\n",
    "\n",
    "model_path = '../artifacts/incident_risk.sav'\n",
    "joblib.dump(best_pipeline, model_path)\n",
    "print(f'Model saved to: {model_path}')\n",
    "print(f'\\nInput features: {numeric_features + categorical_features}')\n",
    "print('\\nProduction scripts:')\n",
    "print('  ETL:       jobs/etl_incident_risk.py')\n",
    "print('  Train:     jobs/train_incident_risk.py')\n",
    "print('  Inference: jobs/run_inference_incident_risk.py')\n",
    "print('\\nPredictions written to PostgreSQL table: incident_risk_predictions')",
]),

code([
    "# Example: score a single resident\n",
    "sample = pd.DataFrame([{\n",
    "    'avg_health_score':          3.1,\n",
    "    'avg_education_attendance':  0.75,\n",
    "    'avg_education_progress':    50.0,\n",
    "    'session_count':             20,\n",
    "    'avg_session_duration':      60.0,\n",
    "    'visit_count':               12,\n",
    "    'length_of_stay':            365,\n",
    "    'initial_risk_level':        'High',\n",
    "    'case_category':             'Surrendered',\n",
    "}])\n",
    "\n",
    "prediction = best_pipeline.predict(sample)\n",
    "proba      = best_pipeline.predict_proba(sample)\n",
    "\n",
    "print(f'Prediction: {\"Has Incident Risk\" if prediction[0] == 1 else \"Low Risk\"}')\n",
    "print(f'Probability -- No Incident: {proba[0][0]:.4f}, Has Incident: {proba[0][1]:.4f}')\n",
    "print(f'\\nRequired input columns: {list(sample.columns)}')",
]),

]

# Load existing notebook to preserve metadata/nbformat
with open('c:/Users/mhawk/Desktop/Security/Intex2/harbor-of-hope/ml-pipelines/05-incident-risk-prediction.ipynb') as f:
    nb = json.load(f)

nb['cells'] = cells

with open('c:/Users/mhawk/Desktop/Security/Intex2/harbor-of-hope/ml-pipelines/05-incident-risk-prediction.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print(f'Wrote {len(cells)} cells successfully.')
